import React from 'react';

export const OnboardingModal: React.FC<{ onAcknowledge: () => void }> = ({ onAcknowledge }) => {
    return (
        <div className="fixed inset-0 bg-gray-900/80 backdrop-blur-sm z-50 flex items-center justify-center fade-in">
            <div className="bg-surface border border-border rounded-2xl shadow-2xl shadow-black/50 w-full max-w-lg m-4 p-8 text-center animate-pop-in">
                <h2 className="text-2xl font-bold mb-4">Welcome to the Integrated Reality Engine</h2>
                <div className="text-left text-text-secondary space-y-4">
                    <p>
                        You are currently in <strong className="text-primary">[SIMULATION]</strong> mode.
                    </p>
                    <p>
                        In this mode, the entire application is a high-fidelity, sandboxed environment. All APIs are mocked, and all data is generated by AI. This allows for risk-free development, testing, and exploration.
                    </p>
                    <p>
                        The <strong className="text-red-400">[LIVE]</strong> mode, accessible via the toggle in the status bar, connects the application to real-world services. Use with caution.
                    </p>
                </div>
                <button
                    onClick={onAcknowledge}
                    className="btn-primary px-8 py-3 mt-8 text-lg"
                >
                    Acknowledge & Begin
                </button>
            </div>
        </div>
    );
};
