import React from 'react';
import type { Feature } from '../../types.ts';
import { RAW_FEATURES } from '../../constants.tsx';
import { lazyWithRetry } from '../../services/componentLoader.ts';

export const componentMap: Record<string, React.LazyExoticComponent<React.FC<any>>> = {
    'pillar-one-geos': lazyWithRetry(() => import('./PillarOneGeos.tsx'), 'PillarOneGeos'),
    'pillar-two-compassion': lazyWithRetry(() => import('./PillarTwoCompassion.tsx'), 'PillarTwoCompassion'),
    'pillar-three-meta-creation': lazyWithRetry(() => import('./PillarThreeMetaCreation.tsx'), 'PillarThreeMetaCreation'),
    'pillar-four-governance': lazyWithRetry(() => import('./PillarFourGovernance.tsx'), 'PillarFourGovernance'),
    'ai-command-center': lazyWithRetry(() => import('./AiCommandCenter.tsx'), 'AiCommandCenter'),
    'project-explorer': lazyWithRetry(() => import('./ProjectExplorer.tsx'), 'ProjectExplorer'),
    'workspace-connector-hub': lazyWithRetry(() => import('./WorkspaceConnectorHub.tsx'), 'WorkspaceConnectorHub'),
    'ai-code-explainer': lazyWithRetry(() => import('../AiCodeExplainer.tsx'), 'AiCodeExplainer'),
    'ai-feature-builder': lazyWithRetry(() => import('./AiFeatureBuilder.tsx'), 'AiFeatureBuilder'),
    'regex-sandbox': lazyWithRetry(() => import('./RegexSandbox.tsx'), 'RegexSandbox'),
    'portable-snippet-vault': lazyWithRetry(() => import('./SnippetVault.tsx'), 'SnippetVault'),
    'css-grid-editor': lazyWithRetry(() => import('./CssGridEditor.tsx'), 'CssGridEditor'),
    'ai-commit-generator': lazyWithRetry(() => import('../AiCommitGenerator.tsx'), 'AiCommitGenerator'),
    'json-tree-navigator': lazyWithRetry(() => import('./JsonTreeNavigator.tsx'), 'JsonTreeNavigator'),
    'xbrl-converter': lazyWithRetry(() => import('./XbrlConverter.tsx'), 'XbrlConverter'),
    'ai-unit-test-generator': lazyWithRetry(() => import('./AiUnitTestGenerator.tsx'), 'AiUnitTestGenerator'),
    'prompt-craft-pad': lazyWithRetry(() => import('./PromptCraftPad.tsx'), 'PromptCraftPad'),
    'linter-formatter': lazyWithRetry(() => import('./CodeFormatter.tsx'), 'CodeFormatter'),
    'schema-designer': lazyWithRetry(() => import('./SchemaDesigner.tsx'), 'SchemaDesigner'),
    'pwa-manifest-editor': lazyWithRetry(() => import('./PwaManifestEditor.tsx'), 'PwaManifestEditor'),
    'markdown-slides-generator': lazyWithRetry(() => import('./MarkdownSlides.tsx'), 'MarkdownSlides'),
    'screenshot-to-component': lazyWithRetry(() => import('./ScreenshotToComponent.tsx'), 'ScreenshotToComponent'),
    'digital-whiteboard': lazyWithRetry(() => import('./DigitalWhiteboard.tsx'), 'DigitalWhiteboard'),
    'theme-designer': lazyWithRetry(() => import('./ThemeDesigner.tsx'), 'ThemeDesigner'),
    'svg-path-editor': lazyWithRetry(() => import('./SvgPathEditor.tsx'), 'SvgPathEditor'),
    'ai-style-transfer': lazyWithRetry(() => import('./AiStyleTransfer.tsx'), 'AiStyleTransfer'),
    'ai-coding-challenge': lazyWithRetry(() => import('../AiCodingChallenge.tsx'), 'AiCodingChallenge'),
    'typography-lab': lazyWithRetry(() => import('./TypographyLab.tsx'), 'TypographyLab'),
    'code-review-bot': lazyWithRetry(() => import('./CodeReviewBot.tsx'), 'CodeReviewBot'),
    'ai-pull-request-assistant': lazyWithRetry(() => import('./AiPullRequestAssistant.tsx'), 'AiPullRequestAssistant'),
    'changelog-generator': lazyWithRetry(() => import('./ChangelogGenerator.tsx'), 'ChangelogGenerator'),
    'cron-job-builder': lazyWithRetry(() => import('./CronJobBuilder.tsx'), 'CronJobBuilder'),
    'ai-code-migrator': lazyWithRetry(() => import('./AiCodeMigrator.tsx'), 'AiCodeMigrator'),
    'visual-git-tree': lazyWithRetry(() => import('./VisualGitTree.tsx'), 'VisualGitTree'),
    'worker-thread-debugger': lazyWithRetry(() => import('./WorkerThreadDebugger.tsx'), 'WorkerThreadDebugger'),
    'ai-image-generator': lazyWithRetry(() => import('./AiImageGenerator.tsx'), 'AiImageGenerator'),
    'async-call-tree-viewer': lazyWithRetry(() => import('./AsyncCallTreeViewer.tsx'), 'AsyncCallTreeViewer'),
    'audio-to-code': lazyWithRetry(() => import('./AudioToCode.tsx'), 'AudioToCode'),
    'code-diff-ghost': lazyWithRetry(() => import('./CodeDiffGhost.tsx'), 'CodeDiffGhost'),
    'code-spell-checker': lazyWithRetry(() => import('./CodeSpellChecker.tsx'), 'CodeSpellChecker'),
    'color-palette-generator': lazyWithRetry(() => import('./ColorPaletteGenerator.tsx'), 'ColorPaletteGenerator'),
    'logic-flow-builder': lazyWithRetry(() => import('./LogicFlowBuilder.tsx'), 'LogicFlowBuilder'),
    'meta-tag-editor': lazyWithRetry(() => import('./MetaTagEditor.tsx'), 'MetaTagEditor'),
    'network-visualizer': lazyWithRetry(() => import('./NetworkVisualizer.tsx'), 'NetworkVisualizer'),
    'responsive-tester': lazyWithRetry(() => import('./ResponsiveTester.tsx'), 'ResponsiveTester'),
    'sass-scss-compiler': lazyWithRetry(() => import('./SassScssCompiler.tsx'), 'SassScssCompiler'),
    'api-mock-generator': lazyWithRetry(() => import('./ApiMockGenerator.tsx'), 'ApiMockGenerator'),
    'env-manager': lazyWithRetry(() => import('./EnvManager.tsx'), 'EnvManager'),
    'performance-profiler': lazyWithRetry(() => import('./PerformanceProfiler.tsx'), 'PerformanceProfiler'),
    'a11y-auditor': lazyWithRetry(() => import('./AccessibilityAuditor.tsx'), 'AccessibilityAuditor'),
    'ci-cd-generator': lazyWithRetry(() => import('./CiCdPipelineGenerator.tsx'), 'CiCdPipelineGenerator'),
    'deployment-preview': lazyWithRetry(() => import('./DeploymentPreview.tsx'), 'DeploymentPreview'),
    'security-scanner': lazyWithRetry(() => import('./SecurityScanner.tsx'), 'SecurityScanner'),
    'terraform-generator': lazyWithRetry(() => import('./TerraformGenerator.tsx'), 'TerraformGenerator'),
    'ai-personality-forge': lazyWithRetry(() => import('./AiPersonalityForge.tsx'), 'AiPersonalityForge'),
    'weekly-digest-generator': lazyWithRetry(() => import('./WeeklyDigestGenerator.tsx'), 'WeeklyDigestGenerator'),
    'one-click-refactor': lazyWithRetry(() => import('./OneClickRefactor.tsx'), 'OneClickRefactor'),
    'bug-reproducer': lazyWithRetry(() => import('./BugReproducer.tsx'), 'BugReproducer'),
    'tech-debt-sonar': lazyWithRetry(() => import('./TechDebtSonar.tsx'), 'TechDebtSonar'),
    'iam-policy-generator': lazyWithRetry(() => import('./IamPolicyGenerator.tsx'), 'IamPolicyGenerator'),
    'iam-policy-visualizer': lazyWithRetry(() => import('./IamPolicyVisualizer.tsx'), 'IamPolicyVisualizer'),
    'gmail-addon-simulator': lazyWithRetry(() => import('./GmailAddonSimulator.tsx'), 'GmailAddonSimulator'),
    
    // --- Implemented Features ---
    'api-client-generator': lazyWithRetry(() => import('./ApiClientGenerator.tsx'), 'ApiClientGenerator'),
    'sql-to-api-generator': lazyWithRetry(() => import('./SqlToApiGenerator.tsx'), 'SqlToApiGenerator'),
    'blameless-postmortem-generator': lazyWithRetry(() => import('./BlamelessPostmortemGenerator.tsx'), 'BlamelessPostmortemGenerator'),
    'data-anonymizer': lazyWithRetry(() => import('./DataAnonymizer.tsx'), 'DataAnonymizer'),
    'a/b-test-assistant': lazyWithRetry(() => import('./ABTestAssistant.tsx'), 'ABTestAssistant'),
    'i18n-helper': lazyWithRetry(() => import('./I18nHelper.tsx'), 'I18nHelper'),
    'token-usage-estimator': lazyWithRetry(() => import('./TokenUsageEstimator.tsx'), 'TokenUsageEstimator'),
    'financial-chart-generator': lazyWithRetry(() => import('./FinancialChartGenerator.tsx'), 'FinancialChartGenerator'),
    'compliance-report-helper': lazyWithRetry(() => import('./ComplianceReportHelper.tsx'), 'ComplianceReportHelper'),
    'ecommerce-component-generator': lazyWithRetry(() => import('./EcommerceComponentGenerator.tsx'), 'EcommerceComponentGenerator'),
    'api-endpoint-tester': lazyWithRetry(() => import('./ApiEndpointTester.tsx'), 'ApiEndpointTester'),
    'storyboard-generator': lazyWithRetry(() => import('./StoryboardGenerator.tsx'), 'StoryboardGenerator'),
    'user-persona-generator': lazyWithRetry(() => import('./UserPersonaGenerator.tsx'), 'UserPersonaGenerator'),
    'competitive-analysis-bot': lazyWithRetry(() => import('./CompetitiveAnalysisBot.tsx'), 'CompetitiveAnalysisBot'),
    'code-documentation-writer': lazyWithRetry(() => import('./CodeDocumentationWriter.tsx'), 'CodeDocumentationWriter'),
    'dependency-update-explainer': lazyWithRetry(() => import('./DependencyUpdateExplainer.tsx'), 'DependencyUpdateExplainer'),
    'ai-video-generator': lazyWithRetry(() => import('./AiVideoGenerator.tsx'), 'AiVideoGenerator'),
    'cloud-cost-estimator': lazyWithRetry(() => import('./CloudCostEstimator.tsx'), 'CloudCostEstimator'),
    'smart-logger': lazyWithRetry(() => import('./SmartLogger.tsx'), 'SmartLogger'),
    'accessibility-annotation': lazyWithRetry(() => import('./AccessibilityAnnotation.tsx'), 'AccessibilityAnnotation'),
    
    // --- Newly Added Features ---
    'wordpress-plugin-generator': lazyWithRetry(() => import('./WordPressPluginGenerator.tsx'), 'WordPressPluginGenerator'),
    'feature-forge': lazyWithRetry(() => import('./FeatureForge.tsx'), 'FeatureForge'),
    'custom-feature-runner': lazyWithRetry(() => import('./CustomFeatureRunner.tsx'), 'CustomFeatureRunner'),

    // --- Profilers ---
    'dom-tree-analyzer': lazyWithRetry(() => import('./DomTreeAnalyzer.tsx'), 'DomTreeAnalyzer'),
    'memory-leak-detector': lazyWithRetry(() => import('./MemoryLeakDetector.tsx'), 'MemoryLeakDetector'),
    'graphql-query-profiler': lazyWithRetry(() => import('./GraphQLQueryProfiler.tsx'), 'GraphQLQueryProfiler'),
    'component-render-tracer': lazyWithRetry(() => import('./ComponentRenderTracer.tsx'), 'ComponentRenderTracer'),
    'seo-auditor': lazyWithRetry(() => import('./SeoAuditor.tsx'), 'SeoAuditor'),

    // --- Utils ---
    'data-transformer': lazyWithRetry(() => import('./DataTransformer.tsx'), 'DataTransformer'),
    'lorem-ipsum-generator': lazyWithRetry(() => import('./LoremIpsumGenerator.tsx'), 'LoremIpsumGenerator'),
    'uuid-generator': lazyWithRetry(() => import('./UuidGenerator.tsx'), 'UuidGenerator'),
    'base64-encoder-decoder': lazyWithRetry(() => import('./Base64EncoderDecoder.tsx'), 'Base64EncoderDecoder'),
    'url-inspector': lazyWithRetry(() => import('./UrlInspector.tsx'), 'UrlInspector'),

    // --- Security ---
    'jwt-inspector': lazyWithRetry(() => import('./JwtInspector.tsx'), 'JwtInspector'),
    'csp-generator': lazyWithRetry(() => import('./CspGenerator.tsx'), 'CspGenerator'),
    'redos-scanner': lazyWithRetry(() => import('./RedosScanner.tsx'), 'RedosScanner'),
    'dependency-vulnerability-scanner': lazyWithRetry(() => import('./DependencyVulnerabilityScanner.tsx'), 'DependencyVulnerabilityScanner'),
    'cors-proxy-simulator': lazyWithRetry(() => import('./CorsProxySimulator.tsx'), 'CorsProxySimulator'),

    // --- Mock ---
    'image-placeholder-generator': lazyWithRetry(() => import('./ImagePlaceholderGenerator.tsx'), 'ImagePlaceholderGenerator'),
    'mock-user-data-generator': lazyWithRetry(() => import('./MockUserDataGenerator.tsx'), 'MockUserDataGenerator'),
    'feature-flag-simulator': lazyWithRetry(() => import('./FeatureFlagSimulator.tsx'), 'FeatureFlagSimulator'),
    'error-response-simulator': lazyWithRetry(() => import('./ErrorResponseSimulator.tsx'), 'ErrorResponseSimulator'),
    'webhook-event-simulator': lazyWithRetry(() => import('./WebhookEventSimulator.tsx'), 'WebhookEventSimulator'),
    
    // --- React Hooks ---
    'usedebounce-hook-generator': lazyWithRetry(() => import('./UseDebounceHookGenerator.tsx'), 'UseDebounceHookGenerator'),
    'uselocalstorage-hook-generator': lazyWithRetry(() => import('./UseLocalStorageHookGenerator.tsx'), 'UseLocalStorageHookGenerator'),
    'useeventlistener-hook-generator': lazyWithRetry(() => import('./UseEventListenerHookGenerator.tsx'), 'UseEventListenerHookGenerator'),
    'usefetch-hook-generator': lazyWithRetry(() => import('./UseFetchHookGenerator.tsx'), 'UseFetchHookGenerator'),
    'useform-hook-generator': lazyWithRetry(() => import('./UseFormHookGenerator.tsx'), 'UseFormHookGenerator'),
};

export const ALL_FEATURES: Feature[] = RAW_FEATURES.map(feature => ({
    ...feature,
    component: componentMap[feature.id],
}));

export const FEATURES_MAP = new Map(ALL_FEATURES.map(f => [f.id, f]));